name: PyLint

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]                                # As of 27/July/2024, Python 3.12 is not attempted because the version of Meson
                                                                                # available is too old for "f2py" to succeed, see the following error last time
                                                                                # I tried:
                                                                                #   * meson.build:1:0: ERROR: Meson version is 0.61.2 but project requires >= 1.1.0
        steps:
            -
                name: Checkout project                                          # https://github.com/actions/checkout
                uses: actions/checkout@v4
                with:
                    path: main
                    submodules: true
            -
                name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5                                   # https://github.com/actions/setup-python
                with:
                    python-version: ${{ matrix.python-version }}
            -
                name: Install f2py dependencies
                run: |
                    sudo apt-get install meson
            -
                name: Install Python ${{ matrix.python-version }} dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r main/requirements.txt
                    pip install -r main/docs/requirements.txt
                    pip install -r main/pyguymer3/f90/fortranlib/requirements.txt
                    pip install git+https://github.com/VACUMM/sphinx-fortran.git@master
                    pip install pylint
            -
                name: List programs
                run: |
                    echo "::notice $(which f2py)"
                    echo "::notice $(which gfortran)"
                    echo "::notice $(which gmake)"
                    echo "::notice $(which meson)"
                    echo "::notice $(which pip)"
                    echo "::notice $(which pylint)"
                    echo "::notice $(which python)"
            -
                name: Analyse the Python ${{ matrix.python-version }} code
                run: |
                    cd main
                    gmake -r -C pyguymer3/f90 FC1=`which f2py` FC2=`which gfortran` PYTHON3=`which python` compile
                    pylint --rcfile=".pylintrc" --errors-only $(git ls-files "*.py")
